name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yopark.dev/not-woowacourse
          stage: main
          yaml: |
            name: my-tiny-backend
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_HOST
                  value: ${{ secrets.CLOUDTYPE_DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.CLOUDTYPE_DB_PORT }}
                - name: DB_USERNAME
                  value: ${{ secrets.CLOUDTYPE_DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.CLOUDTYPE_DB_PASSWORD }}
                - name: DB_NAME
                  value: ${{ secrets.CLOUDTYPE_DB_NAME }}
              ports: 3000
              install: npm install
              build: npm run build
              start: npm run start:prod
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
